### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by Euphorbium** [metzlar-os/cms-form-plugin#1]
Your suggested method of installation does not work. 
    _pip install cms-form-plugin_
gives:  
    _Could not find any downloads that satisfy the requirement cms-form-plugin
Cleaning up...
No distributions at all found for cms-form-plugin_

**Comment by metzlar-os** [comment]
Yeah cms-form-plugin is not part of PyPI yet, you can run the development version using 

pip install -e git+https://github.com/metzlar/cms-form-plugin#egg=cms-form-plugin
