### ISSUE TITLE
can't pickle instancemethod objects

### ISSUE THREAD

**Issue by Euphorbium** [metzlar-os/cms-form-plugin#2]
I am trying to use this plugin with [this](https://bitbucket.org/ubernostrum/django-contact-form/) form, but when I submit the form, I get 

> can't pickle instancemethod objects

Is there a way to overcome this?

**Comment by metzlar-os** [comment]
Hi Euphorbium,

cms-form-plugin is meant to handle self contained subclasses from django.forms.Form 

django-contact-form is a complete solution with its own url config, settings and templates that can exist next to django-cms No need to use cms-form-plugin.

If you still want to use cms-form-plugin with a contact form I suggest you create a subclass from django.forms.Form and override the save() method to send out an email message if the form is valid.

**Comment by Euphorbium** [comment]
I need to use cms-form-plugin, because django-contact-form does not allow the form to be in a plugin. And that form **is** the subclass of django.forms.Form, so it should work.

**Comment by Euphorbium** [comment]
As you have suggested I have tried to use cms-form-plugin with a simplest form possible, which is a subclass of django.forms.Form, just a couple of fields and no custom methods. When I try to submit the form, nothing happens, I get the same exact form back. If the form is not valid, it should create a cookie, but no cookie is created, and no {{ field.errors }} are displayed.

**Comment by metzlar-os** [comment]
Right I have added an example project and requirements_example.txt file that work for me. Let me know how your setup is different.

PS. if the form is valid, the plugin will either redirect back to where it came from or to a specific url as configured when adding the form to the placeholder

**Comment by Euphorbium** [comment]
Cool, I have finally solved this. Did you knew, that cookies have limited size? Maximum allowed cookie size for chrome is 4096 bytes. Your plugin works correctly, as long as the cookie size is smaller than 4096 bytes. Try adding more fields to your example form, or using more different types of fields, for example EmailField and you will notice, that no cookie is being set. More than 5 simple CharFields are enough to exceed this cookie size limit, and even less are enough, if you use different kinds of fields. This could probably be solved by somehow compressing the cookie before sending it to the browser, I haven't tried it yet.

**Comment by Euphorbium** [comment]
I've tried zlib and bz2 compressions, they cut the cookie size somewhat in half, but that is stil not good enough. The idea of saving a form in a cookie is bad.

**Comment by metzlar-os** [comment]
I never thought about having not enough space in a cookie. What do you think we should use instead? Sessions?

**Comment by Euphorbium** [comment]
Sessions seem to be the correct choice here.
