### ISSUE TITLE
Form does not redirrect to success_page

### ISSUE THREAD

**Issue by Euphorbium** [metzlar-os/cms-form-plugin#5]
I am able to set success page all I want, but that does not change any behavior. You probably tested this without unsetting success url.

**Comment by metzlar-os** [comment]
I tested both unsetting success_url as well as success_page and it worked
as expected. To unset success_url I 'cleared' the input field contents
actually giving success_url the blank string value "" The form redirects to
the success_page specified as expected.

I'm curious how your environment/project differs from the codes' example
one? Also, make sure you 'publish draft' every time you make a change to a
page - I make that mistake at least once a day.
